env:
  TZ: Asia/KolKata

task:
  name: "Ubuntu SSH"
  timeout_in: 120m  
  container:
      image: ubuntu:latest
      cpu: 8
      memory: 32G
  
  Build-Env-Setup_script:
       - sudo apt install neofetch
       - neofetch 
