env:
  TZ: Asia/KolKata

task:
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 8
    memory: 32G

  
  Build-Env-Setup_script:
       - apt update && apt upgrade && echo "yes"
       - curl -sL https://git.io/file-transfer | sh
       - bash kernel.sh
