env:
  TZ: Asia/KolKata

task:
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 8
    memory: 32G

  
  Bobo-Bot:
       - apt update && apt upgrade && echo "yes"
       - bash bobo.sh
