env:
  TZ: Asia/KolKata

task:
  name: "Ubuntu SSH"
  container:
      image: cirrus-images/family/docker-builder
      cpu: 8
      memory: 32G
  
  Build-Env-Setup_script:
       - apt update && apt upgrade 
       - bash bot.sh
