env: 
    git_token: "ENCRYPTED[!13d0365a229ce7549b135e0d6c27782d05f7e8417f533f4dcf35b9c456b55968a88d378299f9eac7c81b8ffec3766e93!]"

task:
  name: "JARVIS Builder"
  timeout_in: 240m  
  container:
      image: marvelmathesh/docker:rom
      cpu: 8
      memory: 32G

  Sync_script:
      - bash bot.sh
