env: 
  bot_token: ENCRYPTED[!13b78faf4b4712caa75e6d4fa52ecbc671db5c7399ce6cdb32f1d1956e5a18ff7a474c63b400c7ee2d79240d55cc1e72!]

task:
  name: "Bobo-Bot"
  compute_engine_instance:
      image_project: cirrus-images
      image: family/docker-builder
      platform: linux
      cpu: 8
      memory: 32G

  Sync_script:
      - apt update && apt upgrade && echo "yes"
      - sudo -E apt-get -qq update
      - sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex bison ccache openjdk-8-jdk expect neofetch tmux tmate aria2
      - curl -sL https://git.io/file-transfer | sh

  Clone-Device-shits:
      - git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git -b master ErfanGSIs
      - sudo chmod -R 0777 ErfanGSIs
      - sudo bash ErfanGSIs/setup.sh

  Build_script:
      - java -jar Bobo.jar
      - rm -rf configs/configs.prop && rm -rf configs/sf-creds.prop
      - cd configs
      - touch configs.prop
      - echo "#Bo³+t config file" >> "configs.prop"
      - echo "#Sat Dec 25 12:03:12 GAZA/JERUSALEM PALESTINE 2021" >> "configs.prop"
      - echo "bot-username=Comfee_GSI_bot" >> "configs.prop"
      - echo "bot-token=&{bot_token}" >> "configs.prop"
      - echo "bot-master=2115621788" >> "configs.prop"
      - touch sf-creds.prop
      - echo "#Config file" >> "sf-creds.prop"
      - echo "#Sat Dec 25 12:03:12 GAZA/JERUSALEM PALESTINE 2021" >> "sf-creds.prop"
      - echo "bot-sf-user=jarvis4subhendu" >> "sf-creds.prop"
      - echo "bot-send-announcement=true" >> "sf-creds.prop"
      - echo "bot-sf-proj=nippongsi" >> "sf-creds.prop"
      - echo "bot-announcement-id=-1001446520361" >> "sf-creds.prop"
      - echo "bot-sf-pass=1234_@_Ankita" >> "sf-creds.prop"
      - echo "bot-sf-host=frs.sourceforge.net" >> "sf-creds.prop"

  Upload_script:
      - sudo chmod -R 0777 *
      - sudo java -jar Bobo.jar
