env: 
    git_token: "ENCRYPTED[!13d0365a229ce7549b135e0d6c27782d05f7e8417f533f4dcf35b9c456b55968a88d378299f9eac7c81b8ffec3766e93!]"

task:
  name: "JARVIS Builder"
  timeout_in: 4h 
  persistent_worker:
    labels:
      name: AX61-1
    isolation:
      container:
        image: apon77/aosp:cirrus
        cpu: 24
        memory: 120G
        volumes:
          - /home/cirrus/roms:/home/cirrus/roms
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config

  Sync_script:
      - df -h
      - bash synching.sh

  Cloning_script:
      - bash cloning.sh

  Building_script:
      - bash building.sh

  Uploading_script:
      - bash uploadit.sh
