env:
  TZ: Asia/KolKata

task:
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 16
    memory: 64G

  
  Build-Env-Setup_script:
       - apt update && apt upgrade && echo "yes"
       - bash bot.sh
